[package]
name = "shiny-happiness"
version = "0.1.0"
authors = ["alice <alice@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
